import 'package:tbcxsui/models/models.dart' as model;

List<model.Sneaker> dataSneakers = [
  model.Sneaker(
    name: 'Jordan 11 Retro Concord',
    brand: 'Nike',
    imagePath: 'assets/sneakers/jordan-11-retro-concord.png',
    description: 'The white mesh as well as the black patent leather upper of this Retro Air Jordan 11 model has dark concord accents, while the outsole is dyed blue. On the rear right side of the right shoe is a Jordan logo, while the back left side of the left foot also has the emblem. The sneaker has a white lacing system that completes its appearance.',
    releaseDate: DateTime(2011, 10, 1),
    price: 175.0,
  ),
  model.Sneaker(
    name: 'Nike Air Max 1/97 Sean Wotherspoon',
    brand: 'Nike',
    imagePath: 'assets/sneakers/nike-air-max-sean-wotherspoon.png',
    description: 'This ultra-special Nike Air Max 97/1 was originally part of a Nike design contest that Sean entered and ended up winning. Reportedly inspired by Sean’s love for vintage Nike hats from the 1980s, this shoe features both the upper of the Air Max 97 and the sole unit of the Air Max 1, a killer combo. The shoe also has a unique colorful corduroy upper with frayed edges, a truly one-of-a-kind look, with velour from toe to heel.',
    releaseDate: DateTime(2017, 10, 1),
    price: 160.0,
  ),
  model.Sneaker(
    name: 'Jordan 1 Retro High OG SP Travis Scott Mocha',
    brand: 'Nike',
    imagePath: 'assets/sneakers/jordan-1-retro-high-OG-SP-travis-scott-mocha.png',
    description: 'The Air Jordan 1 Travis Scott features a white leather upper with Mocha suede overlays and black leather reversed Swooshes. Hits of red on the tongue slightly contrast the design\'s earth tones. On the heel, a debossed Cactus Jack logo adds a custom feel. From there, a yellowed midsole and matching Mocha outsole complete the design.',
    releaseDate: DateTime(2019, 10, 1),
    price: 175.0,
  ),
  model.Sneaker(
    name: 'Jordan 1 Retro High Off-White Chicago',
    brand: 'Nike',
    imagePath: 'assets/sneakers/jordan-1-retro-high-off-white-chicago.png',
    description: 'The Off-White x Air Jordan 1 Retro High OG was one of the most highly anticipated footwear collaborations of 2017. It marked the first time Virgil Abloh, founder of the Milan-based fashion label and Jordan Brand had teamed up. Nicknamed "The 10" edition, this pair comes in the original Chicago-themed white, black and varsity red colorway. Featuring a white, red and black-based deconstructed leather upper with a Swooshless medial side branded with "Off-White for Nike Air Jordan 1, Beaverton, Oregon, USA © 1985." Other details include: floppy ankle collars with hidden "85" written on the inside, an oversized off-centered Swoosh on the lateral sides, "Air" written on the midsole and the word "Shoelaces" on the laces with no branding on the tongue.',
    releaseDate: DateTime(2017, 10, 1),
    price: 190.0,
  ),
  model.Sneaker(
    name: 'Adidas Yeezy Boost 750 Light Grey Glow In the Dark',
    brand: 'Adidas',
    imagePath: 'assets/sneakers/adidas-yeezy-boost-750-light-grey-glow-in-the-dark.png',
    description: 'The adidas Yeezy Boost 750 Light Grey Glow In the Dark is a high-level glowing-in-the-dark sneaker. The glowing sneakers detail a light grey patent leather elevated with a flexible mid-foot band.',
    releaseDate: DateTime(2016, 10, 1),
    price: 350.0,
  ),
  model.Sneaker(
    name: 'Nike Air Yeezy 2 Red October',
    brand: 'Nike',
    imagePath: 'assets/sneakers/nike-air-yeezy-2-red-october.png',
    description: 'The Air Yeezy 2 Red October features a distinctive design that includes a molded upper with a reptilian texture. The midsole is composed of Phylon foam, which is lightweight and flexible, providing cushioning for the foot. The Air-Sole unit is in the heel and is visible through a window in the sole, and provides additional cushioning and support. A strap at the front of the shoe helps to secure the foot in place, while the rubber outsole provides traction on a variety of surfaces.',
    releaseDate: DateTime(2014, 10, 1),
    price: 250.0,
  ),
  model.Sneaker(
    name: 'Jordan 1 Retro Black Royal Blue',
    brand: 'Nike',
    imagePath: 'assets/sneakers/jordan-1-retro-black-royal-blue.png',
    description: 'The Black Royal Blue Jordan 1 Retro (2013) has a leather upper, providing durability. The shoe’s high-top design offers ankle support and stability. The shoe also has a lace-up closure system, allowing for a secure and customized fit. The shoe\'s midsole includes Nike Air cushioning, offering impact absorption and comfort. The outsole is made of durable rubber, providing traction and grip. Moreover, the shoe has the signature Air Jordan Wings logo on the collar, the Nike Swoosh on the sides, and the "NIKE Swoosh AIR" insignia on the tongue.',
    releaseDate: DateTime(2013, 10, 1),
    price: 140.0,
  ),
  model.Sneaker(
    name: 'Nike SB Dunk Low Supreme Red Cement',
    brand: 'Nike',
    imagePath: 'assets/sneakers/nike-SB-dunk-low-supreme-red-cement.png',
    description: 'The Red Cement Supreme Dunk Low released in Supreme stores in New York, Los Angeles, London, and Tokyo, making them more accessible than the original versions. Along with the familiar colors and details, the Nike Dunk SB Low Supreme also came with a hang tag keychain featuring the company’s "World Famous" branding. While the original Supreme Dunks might be the most sought after, the Red Cement Supreme Dunks turned out to be a reseller’s dream -- just like we’ve come to expect from Supreme.',
    releaseDate: DateTime(2012, 10, 1),
    price: 148.0,
  ),
  model.Sneaker(
    name: 'Jordan 1 Retro Banned',
    brand: 'Nike',
    imagePath: 'assets/sneakers/jordan-1-retro-banned.png',
    description: 'In 1985, Michael Jordan’s sneakers were "banned" by the NBA during his rookie season for not adhering to the league’s strict dress code. As the story of the Banned Jordans goes, Nike supposedly paid the per-game fines for Jordan to wear the black and red Jordan 1s. Although the Bred colorway of the Jordan 1 had released in 2009, the Banned 1s became the talk of the sneaker community because they featured the original "Nike Air" label on the tongue, along with an "X" on each heel. The insoles read, "On October 18th, 1985, They Were Thrown Out Of The Game."',
    releaseDate: DateTime(2011, 10, 1),
    price: 125.0,
  ),
  model.Sneaker(
    name: 'Nike Mag \'Back To The Future\'',
    brand: 'Nike',
    imagePath: 'assets/sneakers/nike-mag-back-to-the-future.png',
    description: 'Immortalized in the 1989 film \'Back to the Future II,\' the Nike Mag was finally released to the public in September 2011. Though the shoe lacks the self-lacing feature, it’s an aesthetic match to its filmic counterpart, complete with an electroluminescent Nike logo on the strap and glowing LED arrays at the midsole and heel. The 2011 production run was limited to 1500 pairs and released through charity eBay auctions where proceeds went directly to Michael J. Fox’s Foundation in finding a cure for Parkinson\'s Disease.',
    releaseDate: DateTime(2011, 10, 1),
    price: 2300.0,
  ),
  model.Sneaker(
    name: 'Air Foamposite One NRG \'Galaxy\'',
    brand: 'Nike',
    imagePath: 'assets/sneakers/air-foamposite-one-NRG-galaxy.png',
    description: 'A sample of the Nike Air Foamposite One NRG \'Galaxy\' sneaker was first seen on Nike and Jordan executive Gentry Humphrey during the Sole Collector x Penny Hardaway event in 2011. In February 2012, the shoe was released to the public as part of the ‘All-Star’ pack collection. The ‘Galaxy’ themed shoe is outfitted with a signature Foamposite, wavy foam upper with an interior that molds to the shape of the foot. The shoe\'s Zoom Air cushioning provides a responsive feel.',
    releaseDate: DateTime(2012, 10, 1),
    price: 220.0,
  ),
  model.Sneaker(
    name: 'Air Yeezy \'Zen\'',
    brand: 'Nike',
    imagePath: 'assets/sneakers/air-yeezy-zen.png',
    description: 'The Air Yeezy ‘Zen’ launched in April 2009, one of three colorways that made up the first collaborative release from Kanye West and Nike. An overall new silhouette with details borrowed from the Nike archives, the design employs a mostly neutral colorway with vibrantly hued accents throughout. The patent leather midfoot strap comes in a unique texture while the toe cap features premium suede. Underfoot, the nondescript rubber outsole glows green when the lights go down.',
    releaseDate: DateTime(2009, 10, 1),
    price: 250.0,
  ),
];


// List<model.Sneaker> dataSneakers = [
//   model.Sneaker(
//     name: 'Nike Air Max 90',
//     brand: 'Nike',
//     imagePath: 'assets/sneakers/https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9e940d3-2192-434e-a017-072303ce2f14/air-max-90-shoes-DKrDC2.png',
//     description: 'The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle outsole, stitched overlays and classic TPU accents. Fresh colours give a modern look while Max Air cushioning adds comfort to your journey.',
//     releaseDate: DateTime(2021, 10, 1),
//     price: 120.0,
//   ),
//   model.Sneaker(
//     name: 'Nike Air Max 95',
//     brand: 'Nike',
//     imagePath: 'assets/sneakers/https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/01490d04-2d96-4224-9655-a17c427569c4/air-max-95-shoes-3WBGqS.png',
//     description: 'The Nike Air Max 95 made its mark as the first shoe to include visible Nike Air cushioning in the forefoot. The Nike Air Max 95 OG Shoe energises the iconic design with updated materials in a variety of textures and accents.',
//     releaseDate: DateTime(2021, 10, 1),
//     price: 170.0,
//   ),
//   model.Sneaker(
//     name: 'Nike Air Max 97',
//     brand: 'Nike',
//     imagePath: 'assets/sneakers/https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/01490d04-2d96-4224-9655-a17c427569c4/air-max-95-shoes-3WBGqS.png',
//     description: 'The Nike Air Max 97 keeps a sneaker icon going strong with the same design details that made it famous: water-ripple lines, reflective piping and full-length Max Air cushioning.',
//     releaseDate: DateTime(2021, 10, 1),
//     price: 180.0,
//   ),
// ];
